# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'Logging' do

  pod 'Willow', '~> 5.0'

  target 'Model' do
  
    # Pods for Model
  
    target 'ModelTests' do
      inherit! :search_paths
      # Pods for testing
    end

    target 'Networking' do
      
      pod 'Alamofire'
      
      target 'Service' do
      
        pod 'KeychainAccess'
        
        target 'ServiceTests' do
          inherit! :search_paths
          # Pods for testing
        end

        target 'FitnessEvents' do
        
          pod 'SDWebImage', '~> 4.0'
          pod 'Fabric'
          pod 'Crashlytics'
          pod 'ValidationComponents'
        end
      end
    end
  end
end
